services:
  - type: web
    name: tta-web
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20.10.0
      - key: NODE_ENV
        value: production
      - key: AIRTABLE_API_KEY
        sync: false
      - key: AIRTABLE_BASE_ID
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
      - key: NEXT_PUBLIC_N8N_COMMUNITY_WEBHOOK
        sync: false
      - key: NEXT_PUBLIC_N8N_EVENT_WEBHOOK
        sync: false
